export const ALL_ANIMALS_REQUEST = 'ALL_ANIMALS_REQUEST'
export const ALL_ANIMALS_SUCCESS = 'ALL_ANIMALS_SUCCESS'
export const ALL_ANIMALS_FAIL = 'ALL_ANIMALS_FAIL'


export const NEW_ANIMAL_REQUEST = 'NEW_ANIMAL_REQUEST'
export const NEW_ANIMAL_SUCCESS = 'NEW_ANIMAL_SUCCESS'
export const NEW_ANIMAL_RESET = 'NEW_ANIMAL_RESET'
export const NEW_ANIMAL_FAIL = 'NEW_ANIMAL_FAIL'

export const UPDATE_ANIMAL_REQUEST = 'UPDATE_ANIMAL_REQUEST'
export const UPDATE_ANIMAL_SUCCESS = 'UPDATE_ANIMAL_SUCCESS'
export const UPDATE_ANIMAL_RESET = 'UPDATE_ANIMAL_RESET'
export const UPDATE_ANIMAL_FAIL = 'UPDATE_ANIMAL_FAIL'

export const ANIMAL_DETAILS_REQUEST = 'ANIMAL_DETAILS_REQUEST'
export const ANIMAL_DETAILS_SUCCESS = 'ANIMAL_DETAILS_SUCCESS'
export const ANIMAL_DETAILS_FAIL = 'ANIMAL_DETAILS_FAIL'
export const ANIMAL_DETAILS_RESET = 'ANIMAL_DETAILS_RESET'

export const DELETE_ANIMAL_REQUEST = 'DELETE_ANIMAL_REQUEST'
export const DELETE_ANIMAL_SUCCESS = 'DELETE_ANIMAL_SUCCESS'
export const DELETE_ANIMAL_RESET = 'DELETE_ANIMAL_RESET'
export const DELETE_ANIMAL_FAIL = 'DELETE_ANIMAL_FAIL'

export const MONTHLY_RESCUED_ANIMAL_REQUEST = 'MONTHLY_RESCUED_ANIMAL_REQUEST'
export const MONTHLY_RESCUED_ANIMAL_SUCCESS = 'MONTHLY_RESCUED_ANIMAL_SUCCESS'
export const MONTHLY_RESCUED_ANIMAL_RESET = 'MONTHLY_RESCUED_ANIMAL_RESET'
export const MONTHLY_RESCUED_ANIMAL_FAIL = 'MONTHLY_RESCUED_ANIMAL_FAIL'


export const MONTHLY_ADOPTED_ANIMAL_REQUEST = 'MONTHLY_ADOPTED_ANIMAL_REQUEST'
export const MONTHLY_ADOPTED_ANIMAL_SUCCESS = 'MONTHLY_ADOPTED_ANIMAL_SUCCESS'
export const MONTHLY_ADOPTED_ANIMAL_RESET = 'MONTHLY_ADOPTED_ANIMAL_RESET'
export const MONTHLY_ADOPTED_ANIMAL_FAIL = 'MONTHLY_ADOPTED_ANIMAL_FAIL'

export const NEW_COMMENT_REQUEST = 'NEW_COMMENT_REQUEST'
export const NEW_COMMENT_SUCCESS = 'NEW_COMMENT_SUCCESS'
export const NEW_COMMENT_RESET = 'NEW_COMMENT_RESET'
export const NEW_COMMENT_FAIL = 'NEW_COMMENT_FAIL'

export const ADOPT_REQUEST = 'ADOPT_REQUEST'
export const ADOPT_SUCCESS = 'ADOPT_SUCCESS'
export const ADOPT_RESET = 'ADOPT_RESET'
export const ADOPT_FAIL = 'ADOPT_FAIL'

export const ADOPT_ACCEPT_REQUEST = 'ADOPT_ACCEPT_REQUEST'
export const ADOPT_ACCEPT_SUCCESS = 'ADOPT_ACCEPT_SUCCESS'
export const ADOPT_ACCEPT_RESET = 'ADOPT_ACCEPT_RESET'
export const ADOPT_ACCEPT_FAIL = 'ADOPT_ACCEPT_FAIL'


export const ADOPT_DECLINE_REQUEST = 'ADOPT_DECLINE_REQUEST'
export const ADOPT_DECLINE_SUCCESS = 'ADOPT_DECLINE_SUCCESS'
export const ADOPT_DECLINE_RESET = 'ADOPT_DECLINE_RESET'
export const ADOPT_DECLINE_FAIL = 'ADOPT_DECLINE_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'